spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123456
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true
